//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace pcompone_1453Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pcompone_1453Entities3 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pcompone_1453Entities3 object using the connection string found in the 'pcompone_1453Entities3' section of the application configuration file.
        /// </summary>
        public pcompone_1453Entities3() : base("name=pcompone_1453Entities3", "pcompone_1453Entities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pcompone_1453Entities3 object.
        /// </summary>
        public pcompone_1453Entities3(string connectionString) : base(connectionString, "pcompone_1453Entities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pcompone_1453Entities3 object.
        /// </summary>
        public pcompone_1453Entities3(EntityConnection connection) : base(connection, "pcompone_1453Entities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dilek_Sikayet> Dilek_Sikayet
        {
            get
            {
                if ((_Dilek_Sikayet == null))
                {
                    _Dilek_Sikayet = base.CreateObjectSet<Dilek_Sikayet>("Dilek_Sikayet");
                }
                return _Dilek_Sikayet;
            }
        }
        private ObjectSet<Dilek_Sikayet> _Dilek_Sikayet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hit> Hit
        {
            get
            {
                if ((_Hit == null))
                {
                    _Hit = base.CreateObjectSet<Hit>("Hit");
                }
                return _Hit;
            }
        }
        private ObjectSet<Hit> _Hit;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kategori> Kategori
        {
            get
            {
                if ((_Kategori == null))
                {
                    _Kategori = base.CreateObjectSet<Kategori>("Kategori");
                }
                return _Kategori;
            }
        }
        private ObjectSet<Kategori> _Kategori;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kullanici> Kullanici
        {
            get
            {
                if ((_Kullanici == null))
                {
                    _Kullanici = base.CreateObjectSet<Kullanici>("Kullanici");
                }
                return _Kullanici;
            }
        }
        private ObjectSet<Kullanici> _Kullanici;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Markalar> Markalar
        {
            get
            {
                if ((_Markalar == null))
                {
                    _Markalar = base.CreateObjectSet<Markalar>("Markalar");
                }
                return _Markalar;
            }
        }
        private ObjectSet<Markalar> _Markalar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Urunler> Urunler
        {
            get
            {
                if ((_Urunler == null))
                {
                    _Urunler = base.CreateObjectSet<Urunler>("Urunler");
                }
                return _Urunler;
            }
        }
        private ObjectSet<Urunler> _Urunler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Yorumlar> Yorumlar
        {
            get
            {
                if ((_Yorumlar == null))
                {
                    _Yorumlar = base.CreateObjectSet<Yorumlar>("Yorumlar");
                }
                return _Yorumlar;
            }
        }
        private ObjectSet<Yorumlar> _Yorumlar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ziyaretci> Ziyaretci
        {
            get
            {
                if ((_Ziyaretci == null))
                {
                    _Ziyaretci = base.CreateObjectSet<Ziyaretci>("Ziyaretci");
                }
                return _Ziyaretci;
            }
        }
        private ObjectSet<Ziyaretci> _Ziyaretci;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FavoriUrunler> FavoriUrunler
        {
            get
            {
                if ((_FavoriUrunler == null))
                {
                    _FavoriUrunler = base.CreateObjectSet<FavoriUrunler>("FavoriUrunler");
                }
                return _FavoriUrunler;
            }
        }
        private ObjectSet<FavoriUrunler> _FavoriUrunler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SatilanUrunler> SatilanUrunler
        {
            get
            {
                if ((_SatilanUrunler == null))
                {
                    _SatilanUrunler = base.CreateObjectSet<SatilanUrunler>("SatilanUrunler");
                }
                return _SatilanUrunler;
            }
        }
        private ObjectSet<SatilanUrunler> _SatilanUrunler;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dilek_Sikayet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDilek_Sikayet(Dilek_Sikayet dilek_Sikayet)
        {
            base.AddObject("Dilek_Sikayet", dilek_Sikayet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hit EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHit(Hit hit)
        {
            base.AddObject("Hit", hit);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kategori EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKategori(Kategori kategori)
        {
            base.AddObject("Kategori", kategori);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kullanici EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKullanici(Kullanici kullanici)
        {
            base.AddObject("Kullanici", kullanici);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Markalar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarkalar(Markalar markalar)
        {
            base.AddObject("Markalar", markalar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Urunler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUrunler(Urunler urunler)
        {
            base.AddObject("Urunler", urunler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Yorumlar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToYorumlar(Yorumlar yorumlar)
        {
            base.AddObject("Yorumlar", yorumlar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ziyaretci EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZiyaretci(Ziyaretci ziyaretci)
        {
            base.AddObject("Ziyaretci", ziyaretci);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FavoriUrunler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFavoriUrunler(FavoriUrunler favoriUrunler)
        {
            base.AddObject("FavoriUrunler", favoriUrunler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SatilanUrunler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSatilanUrunler(SatilanUrunler satilanUrunler)
        {
            base.AddObject("SatilanUrunler", satilanUrunler);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="Dilek_Sikayet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dilek_Sikayet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dilek_Sikayet object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Dilek_Sikayet CreateDilek_Sikayet(global::System.Int32 id)
        {
            Dilek_Sikayet dilek_Sikayet = new Dilek_Sikayet();
            dilek_Sikayet.id = id;
            return dilek_Sikayet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String isim
        {
            get
            {
                return _isim;
            }
            set
            {
                OnisimChanging(value);
                ReportPropertyChanging("isim");
                _isim = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("isim");
                OnisimChanged();
            }
        }
        private global::System.String _isim;
        partial void OnisimChanging(global::System.String value);
        partial void OnisimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String konu
        {
            get
            {
                return _konu;
            }
            set
            {
                OnkonuChanging(value);
                ReportPropertyChanging("konu");
                _konu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("konu");
                OnkonuChanged();
            }
        }
        private global::System.String _konu;
        partial void OnkonuChanging(global::System.String value);
        partial void OnkonuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mesaj
        {
            get
            {
                return _mesaj;
            }
            set
            {
                OnmesajChanging(value);
                ReportPropertyChanging("mesaj");
                _mesaj = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mesaj");
                OnmesajChanged();
            }
        }
        private global::System.String _mesaj;
        partial void OnmesajChanging(global::System.String value);
        partial void OnmesajChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> yazılmatarihi
        {
            get
            {
                return _yazılmatarihi;
            }
            set
            {
                OnyazılmatarihiChanging(value);
                ReportPropertyChanging("yazılmatarihi");
                _yazılmatarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("yazılmatarihi");
                OnyazılmatarihiChanged();
            }
        }
        private Nullable<global::System.DateTime> _yazılmatarihi;
        partial void OnyazılmatarihiChanging(Nullable<global::System.DateTime> value);
        partial void OnyazılmatarihiChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="FavoriUrunler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FavoriUrunler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FavoriUrunler object.
        /// </summary>
        /// <param name="favoriurunID">Initial value of the favoriurunID property.</param>
        /// <param name="urunID">Initial value of the urunID property.</param>
        /// <param name="kullaniciID">Initial value of the kullaniciID property.</param>
        /// <param name="datetime">Initial value of the datetime property.</param>
        public static FavoriUrunler CreateFavoriUrunler(global::System.Int32 favoriurunID, global::System.Int32 urunID, global::System.Int32 kullaniciID, global::System.DateTime datetime)
        {
            FavoriUrunler favoriUrunler = new FavoriUrunler();
            favoriUrunler.favoriurunID = favoriurunID;
            favoriUrunler.urunID = urunID;
            favoriUrunler.kullaniciID = kullaniciID;
            favoriUrunler.datetime = datetime;
            return favoriUrunler;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 favoriurunID
        {
            get
            {
                return _favoriurunID;
            }
            set
            {
                if (_favoriurunID != value)
                {
                    OnfavoriurunIDChanging(value);
                    ReportPropertyChanging("favoriurunID");
                    _favoriurunID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("favoriurunID");
                    OnfavoriurunIDChanged();
                }
            }
        }
        private global::System.Int32 _favoriurunID;
        partial void OnfavoriurunIDChanging(global::System.Int32 value);
        partial void OnfavoriurunIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 urunID
        {
            get
            {
                return _urunID;
            }
            set
            {
                OnurunIDChanging(value);
                ReportPropertyChanging("urunID");
                _urunID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urunID");
                OnurunIDChanged();
            }
        }
        private global::System.Int32 _urunID;
        partial void OnurunIDChanging(global::System.Int32 value);
        partial void OnurunIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kullaniciID
        {
            get
            {
                return _kullaniciID;
            }
            set
            {
                OnkullaniciIDChanging(value);
                ReportPropertyChanging("kullaniciID");
                _kullaniciID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kullaniciID");
                OnkullaniciIDChanged();
            }
        }
        private global::System.Int32 _kullaniciID;
        partial void OnkullaniciIDChanging(global::System.Int32 value);
        partial void OnkullaniciIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datetime
        {
            get
            {
                return _datetime;
            }
            set
            {
                OndatetimeChanging(value);
                ReportPropertyChanging("datetime");
                _datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datetime");
                OndatetimeChanged();
            }
        }
        private global::System.DateTime _datetime;
        partial void OndatetimeChanging(global::System.DateTime value);
        partial void OndatetimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="Hit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hit : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hit object.
        /// </summary>
        /// <param name="hit_id">Initial value of the hit_id property.</param>
        public static Hit CreateHit(global::System.Int32 hit_id)
        {
            Hit hit = new Hit();
            hit.hit_id = hit_id;
            return hit;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hit_id
        {
            get
            {
                return _hit_id;
            }
            set
            {
                if (_hit_id != value)
                {
                    Onhit_idChanging(value);
                    ReportPropertyChanging("hit_id");
                    _hit_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hit_id");
                    Onhit_idChanged();
                }
            }
        }
        private global::System.Int32 _hit_id;
        partial void Onhit_idChanging(global::System.Int32 value);
        partial void Onhit_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> site_hit
        {
            get
            {
                return _site_hit;
            }
            set
            {
                Onsite_hitChanging(value);
                ReportPropertyChanging("site_hit");
                _site_hit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("site_hit");
                Onsite_hitChanged();
            }
        }
        private Nullable<global::System.Int32> _site_hit;
        partial void Onsite_hitChanging(Nullable<global::System.Int32> value);
        partial void Onsite_hitChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="Kategori")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kategori : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kategori object.
        /// </summary>
        /// <param name="kategori_id">Initial value of the kategori_id property.</param>
        public static Kategori CreateKategori(global::System.Int32 kategori_id)
        {
            Kategori kategori = new Kategori();
            kategori.kategori_id = kategori_id;
            return kategori;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kategori_id
        {
            get
            {
                return _kategori_id;
            }
            set
            {
                if (_kategori_id != value)
                {
                    Onkategori_idChanging(value);
                    ReportPropertyChanging("kategori_id");
                    _kategori_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("kategori_id");
                    Onkategori_idChanged();
                }
            }
        }
        private global::System.Int32 _kategori_id;
        partial void Onkategori_idChanging(global::System.Int32 value);
        partial void Onkategori_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kategoriismi
        {
            get
            {
                return _kategoriismi;
            }
            set
            {
                OnkategoriismiChanging(value);
                ReportPropertyChanging("kategoriismi");
                _kategoriismi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kategoriismi");
                OnkategoriismiChanged();
            }
        }
        private global::System.String _kategoriismi;
        partial void OnkategoriismiChanging(global::System.String value);
        partial void OnkategoriismiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MainKategori
        {
            get
            {
                return _MainKategori;
            }
            set
            {
                OnMainKategoriChanging(value);
                ReportPropertyChanging("MainKategori");
                _MainKategori = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MainKategori");
                OnMainKategoriChanged();
            }
        }
        private Nullable<global::System.Int32> _MainKategori;
        partial void OnMainKategoriChanging(Nullable<global::System.Int32> value);
        partial void OnMainKategoriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AnaKategorisi
        {
            get
            {
                return _AnaKategorisi;
            }
            set
            {
                OnAnaKategorisiChanging(value);
                ReportPropertyChanging("AnaKategorisi");
                _AnaKategorisi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AnaKategorisi");
                OnAnaKategorisiChanged();
            }
        }
        private Nullable<global::System.Int32> _AnaKategorisi;
        partial void OnAnaKategorisiChanging(Nullable<global::System.Int32> value);
        partial void OnAnaKategorisiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> urun_markaid
        {
            get
            {
                return _urun_markaid;
            }
            set
            {
                Onurun_markaidChanging(value);
                ReportPropertyChanging("urun_markaid");
                _urun_markaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urun_markaid");
                Onurun_markaidChanged();
            }
        }
        private Nullable<global::System.Int32> _urun_markaid;
        partial void Onurun_markaidChanging(Nullable<global::System.Int32> value);
        partial void Onurun_markaidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="Kullanici")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kullanici : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kullanici object.
        /// </summary>
        /// <param name="kullanici_id">Initial value of the kullanici_id property.</param>
        public static Kullanici CreateKullanici(global::System.Int32 kullanici_id)
        {
            Kullanici kullanici = new Kullanici();
            kullanici.kullanici_id = kullanici_id;
            return kullanici;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kullanici_id
        {
            get
            {
                return _kullanici_id;
            }
            set
            {
                if (_kullanici_id != value)
                {
                    Onkullanici_idChanging(value);
                    ReportPropertyChanging("kullanici_id");
                    _kullanici_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("kullanici_id");
                    Onkullanici_idChanged();
                }
            }
        }
        private global::System.Int32 _kullanici_id;
        partial void Onkullanici_idChanging(global::System.Int32 value);
        partial void Onkullanici_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adi
        {
            get
            {
                return _adi;
            }
            set
            {
                OnadiChanging(value);
                ReportPropertyChanging("adi");
                _adi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adi");
                OnadiChanged();
            }
        }
        private global::System.String _adi;
        partial void OnadiChanging(global::System.String value);
        partial void OnadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String soyadi
        {
            get
            {
                return _soyadi;
            }
            set
            {
                OnsoyadiChanging(value);
                ReportPropertyChanging("soyadi");
                _soyadi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("soyadi");
                OnsoyadiChanged();
            }
        }
        private global::System.String _soyadi;
        partial void OnsoyadiChanging(global::System.String value);
        partial void OnsoyadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kullaniciadi
        {
            get
            {
                return _kullaniciadi;
            }
            set
            {
                OnkullaniciadiChanging(value);
                ReportPropertyChanging("kullaniciadi");
                _kullaniciadi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kullaniciadi");
                OnkullaniciadiChanged();
            }
        }
        private global::System.String _kullaniciadi;
        partial void OnkullaniciadiChanging(global::System.String value);
        partial void OnkullaniciadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sifre
        {
            get
            {
                return _sifre;
            }
            set
            {
                OnsifreChanging(value);
                ReportPropertyChanging("sifre");
                _sifre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sifre");
                OnsifreChanged();
            }
        }
        private global::System.String _sifre;
        partial void OnsifreChanging(global::System.String value);
        partial void OnsifreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dogumtarihi
        {
            get
            {
                return _dogumtarihi;
            }
            set
            {
                OndogumtarihiChanging(value);
                ReportPropertyChanging("dogumtarihi");
                _dogumtarihi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dogumtarihi");
                OndogumtarihiChanged();
            }
        }
        private global::System.String _dogumtarihi;
        partial void OndogumtarihiChanging(global::System.String value);
        partial void OndogumtarihiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dogumyeri
        {
            get
            {
                return _dogumyeri;
            }
            set
            {
                OndogumyeriChanging(value);
                ReportPropertyChanging("dogumyeri");
                _dogumyeri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dogumyeri");
                OndogumyeriChanged();
            }
        }
        private global::System.String _dogumyeri;
        partial void OndogumyeriChanging(global::System.String value);
        partial void OndogumyeriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sehir
        {
            get
            {
                return _sehir;
            }
            set
            {
                OnsehirChanging(value);
                ReportPropertyChanging("sehir");
                _sehir = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sehir");
                OnsehirChanged();
            }
        }
        private global::System.String _sehir;
        partial void OnsehirChanging(global::System.String value);
        partial void OnsehirChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adres
        {
            get
            {
                return _adres;
            }
            set
            {
                OnadresChanging(value);
                ReportPropertyChanging("adres");
                _adres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adres");
                OnadresChanged();
            }
        }
        private global::System.String _adres;
        partial void OnadresChanging(global::System.String value);
        partial void OnadresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ceptelefonu
        {
            get
            {
                return _ceptelefonu;
            }
            set
            {
                OnceptelefonuChanging(value);
                ReportPropertyChanging("ceptelefonu");
                _ceptelefonu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ceptelefonu");
                OnceptelefonuChanged();
            }
        }
        private global::System.String _ceptelefonu;
        partial void OnceptelefonuChanging(global::System.String value);
        partial void OnceptelefonuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kisi_soru
        {
            get
            {
                return _kisi_soru;
            }
            set
            {
                Onkisi_soruChanging(value);
                ReportPropertyChanging("kisi_soru");
                _kisi_soru = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kisi_soru");
                Onkisi_soruChanged();
            }
        }
        private global::System.String _kisi_soru;
        partial void Onkisi_soruChanging(global::System.String value);
        partial void Onkisi_soruChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kisi_cevap
        {
            get
            {
                return _kisi_cevap;
            }
            set
            {
                Onkisi_cevapChanging(value);
                ReportPropertyChanging("kisi_cevap");
                _kisi_cevap = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kisi_cevap");
                Onkisi_cevapChanged();
            }
        }
        private global::System.String _kisi_cevap;
        partial void Onkisi_cevapChanging(global::System.String value);
        partial void Onkisi_cevapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> aktiflik
        {
            get
            {
                return _aktiflik;
            }
            set
            {
                OnaktiflikChanging(value);
                ReportPropertyChanging("aktiflik");
                _aktiflik = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aktiflik");
                OnaktiflikChanged();
            }
        }
        private Nullable<global::System.Int32> _aktiflik;
        partial void OnaktiflikChanging(Nullable<global::System.Int32> value);
        partial void OnaktiflikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> durum
        {
            get
            {
                return _durum;
            }
            set
            {
                OndurumChanging(value);
                ReportPropertyChanging("durum");
                _durum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("durum");
                OndurumChanged();
            }
        }
        private Nullable<global::System.Int32> _durum;
        partial void OndurumChanging(Nullable<global::System.Int32> value);
        partial void OndurumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kullanicikimligi
        {
            get
            {
                return _kullanicikimligi;
            }
            set
            {
                OnkullanicikimligiChanging(value);
                ReportPropertyChanging("kullanicikimligi");
                _kullanicikimligi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kullanicikimligi");
                OnkullanicikimligiChanged();
            }
        }
        private global::System.String _kullanicikimligi;
        partial void OnkullanicikimligiChanging(global::System.String value);
        partial void OnkullanicikimligiChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="Markalar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Markalar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Markalar object.
        /// </summary>
        /// <param name="marka_id">Initial value of the marka_id property.</param>
        public static Markalar CreateMarkalar(global::System.Int32 marka_id)
        {
            Markalar markalar = new Markalar();
            markalar.marka_id = marka_id;
            return markalar;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 marka_id
        {
            get
            {
                return _marka_id;
            }
            set
            {
                if (_marka_id != value)
                {
                    Onmarka_idChanging(value);
                    ReportPropertyChanging("marka_id");
                    _marka_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("marka_id");
                    Onmarka_idChanged();
                }
            }
        }
        private global::System.Int32 _marka_id;
        partial void Onmarka_idChanging(global::System.Int32 value);
        partial void Onmarka_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String markaismi
        {
            get
            {
                return _markaismi;
            }
            set
            {
                OnmarkaismiChanging(value);
                ReportPropertyChanging("markaismi");
                _markaismi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("markaismi");
                OnmarkaismiChanged();
            }
        }
        private global::System.String _markaismi;
        partial void OnmarkaismiChanging(global::System.String value);
        partial void OnmarkaismiChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="SatilanUrunler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SatilanUrunler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SatilanUrunler object.
        /// </summary>
        /// <param name="satilanurunID">Initial value of the satilanurunID property.</param>
        /// <param name="urunID">Initial value of the urunID property.</param>
        /// <param name="kullaniciID">Initial value of the kullaniciID property.</param>
        public static SatilanUrunler CreateSatilanUrunler(global::System.Int32 satilanurunID, global::System.Int32 urunID, global::System.Int32 kullaniciID)
        {
            SatilanUrunler satilanUrunler = new SatilanUrunler();
            satilanUrunler.satilanurunID = satilanurunID;
            satilanUrunler.urunID = urunID;
            satilanUrunler.kullaniciID = kullaniciID;
            return satilanUrunler;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 satilanurunID
        {
            get
            {
                return _satilanurunID;
            }
            set
            {
                if (_satilanurunID != value)
                {
                    OnsatilanurunIDChanging(value);
                    ReportPropertyChanging("satilanurunID");
                    _satilanurunID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("satilanurunID");
                    OnsatilanurunIDChanged();
                }
            }
        }
        private global::System.Int32 _satilanurunID;
        partial void OnsatilanurunIDChanging(global::System.Int32 value);
        partial void OnsatilanurunIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 urunID
        {
            get
            {
                return _urunID;
            }
            set
            {
                OnurunIDChanging(value);
                ReportPropertyChanging("urunID");
                _urunID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urunID");
                OnurunIDChanged();
            }
        }
        private global::System.Int32 _urunID;
        partial void OnurunIDChanging(global::System.Int32 value);
        partial void OnurunIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kullaniciID
        {
            get
            {
                return _kullaniciID;
            }
            set
            {
                OnkullaniciIDChanging(value);
                ReportPropertyChanging("kullaniciID");
                _kullaniciID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kullaniciID");
                OnkullaniciIDChanged();
            }
        }
        private global::System.Int32 _kullaniciID;
        partial void OnkullaniciIDChanging(global::System.Int32 value);
        partial void OnkullaniciIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datetime
        {
            get
            {
                return _datetime;
            }
            set
            {
                OndatetimeChanging(value);
                ReportPropertyChanging("datetime");
                _datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datetime");
                OndatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _datetime;
        partial void OndatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OndatetimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> urunadedi
        {
            get
            {
                return _urunadedi;
            }
            set
            {
                OnurunadediChanging(value);
                ReportPropertyChanging("urunadedi");
                _urunadedi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urunadedi");
                OnurunadediChanged();
            }
        }
        private Nullable<global::System.Int32> _urunadedi;
        partial void OnurunadediChanging(Nullable<global::System.Int32> value);
        partial void OnurunadediChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> toplamfiyat
        {
            get
            {
                return _toplamfiyat;
            }
            set
            {
                OntoplamfiyatChanging(value);
                ReportPropertyChanging("toplamfiyat");
                _toplamfiyat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("toplamfiyat");
                OntoplamfiyatChanged();
            }
        }
        private Nullable<global::System.Int32> _toplamfiyat;
        partial void OntoplamfiyatChanging(Nullable<global::System.Int32> value);
        partial void OntoplamfiyatChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="Urunler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Urunler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Urunler object.
        /// </summary>
        /// <param name="urun_id">Initial value of the urun_id property.</param>
        /// <param name="urunKategoriID">Initial value of the urunKategoriID property.</param>
        /// <param name="urun_markaid">Initial value of the urun_markaid property.</param>
        /// <param name="urunsatissayisi">Initial value of the urunsatissayisi property.</param>
        public static Urunler CreateUrunler(global::System.Int32 urun_id, global::System.Int32 urunKategoriID, global::System.Int32 urun_markaid, global::System.Int32 urunsatissayisi)
        {
            Urunler urunler = new Urunler();
            urunler.urun_id = urun_id;
            urunler.urunKategoriID = urunKategoriID;
            urunler.urun_markaid = urun_markaid;
            urunler.urunsatissayisi = urunsatissayisi;
            return urunler;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 urun_id
        {
            get
            {
                return _urun_id;
            }
            set
            {
                if (_urun_id != value)
                {
                    Onurun_idChanging(value);
                    ReportPropertyChanging("urun_id");
                    _urun_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("urun_id");
                    Onurun_idChanged();
                }
            }
        }
        private global::System.Int32 _urun_id;
        partial void Onurun_idChanging(global::System.Int32 value);
        partial void Onurun_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String urunismi
        {
            get
            {
                return _urunismi;
            }
            set
            {
                OnurunismiChanging(value);
                ReportPropertyChanging("urunismi");
                _urunismi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("urunismi");
                OnurunismiChanged();
            }
        }
        private global::System.String _urunismi;
        partial void OnurunismiChanging(global::System.String value);
        partial void OnurunismiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fiyat
        {
            get
            {
                return _fiyat;
            }
            set
            {
                OnfiyatChanging(value);
                ReportPropertyChanging("fiyat");
                _fiyat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fiyat");
                OnfiyatChanged();
            }
        }
        private Nullable<global::System.Int32> _fiyat;
        partial void OnfiyatChanging(Nullable<global::System.Int32> value);
        partial void OnfiyatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resim
        {
            get
            {
                return _resim;
            }
            set
            {
                OnresimChanging(value);
                ReportPropertyChanging("resim");
                _resim = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resim");
                OnresimChanged();
            }
        }
        private global::System.String _resim;
        partial void OnresimChanging(global::System.String value);
        partial void OnresimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String durum
        {
            get
            {
                return _durum;
            }
            set
            {
                OndurumChanging(value);
                ReportPropertyChanging("durum");
                _durum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("durum");
                OndurumChanged();
            }
        }
        private global::System.String _durum;
        partial void OndurumChanging(global::System.String value);
        partial void OndurumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ozellikler
        {
            get
            {
                return _ozellikler;
            }
            set
            {
                OnozelliklerChanging(value);
                ReportPropertyChanging("ozellikler");
                _ozellikler = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ozellikler");
                OnozelliklerChanged();
            }
        }
        private global::System.String _ozellikler;
        partial void OnozelliklerChanging(global::System.String value);
        partial void OnozelliklerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String garantisuresi
        {
            get
            {
                return _garantisuresi;
            }
            set
            {
                OngarantisuresiChanging(value);
                ReportPropertyChanging("garantisuresi");
                _garantisuresi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("garantisuresi");
                OngarantisuresiChanged();
            }
        }
        private global::System.String _garantisuresi;
        partial void OngarantisuresiChanging(global::System.String value);
        partial void OngarantisuresiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String urunturu
        {
            get
            {
                return _urunturu;
            }
            set
            {
                OnurunturuChanging(value);
                ReportPropertyChanging("urunturu");
                _urunturu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("urunturu");
                OnurunturuChanged();
            }
        }
        private global::System.String _urunturu;
        partial void OnurunturuChanging(global::System.String value);
        partial void OnurunturuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 urunKategoriID
        {
            get
            {
                return _urunKategoriID;
            }
            set
            {
                OnurunKategoriIDChanging(value);
                ReportPropertyChanging("urunKategoriID");
                _urunKategoriID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urunKategoriID");
                OnurunKategoriIDChanged();
            }
        }
        private global::System.Int32 _urunKategoriID;
        partial void OnurunKategoriIDChanging(global::System.Int32 value);
        partial void OnurunKategoriIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> eklenmetarihi
        {
            get
            {
                return _eklenmetarihi;
            }
            set
            {
                OneklenmetarihiChanging(value);
                ReportPropertyChanging("eklenmetarihi");
                _eklenmetarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eklenmetarihi");
                OneklenmetarihiChanged();
            }
        }
        private Nullable<global::System.DateTime> _eklenmetarihi;
        partial void OneklenmetarihiChanging(Nullable<global::System.DateTime> value);
        partial void OneklenmetarihiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 urun_markaid
        {
            get
            {
                return _urun_markaid;
            }
            set
            {
                Onurun_markaidChanging(value);
                ReportPropertyChanging("urun_markaid");
                _urun_markaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urun_markaid");
                Onurun_markaidChanged();
            }
        }
        private global::System.Int32 _urun_markaid;
        partial void Onurun_markaidChanging(global::System.Int32 value);
        partial void Onurun_markaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String urun_markaismi
        {
            get
            {
                return _urun_markaismi;
            }
            set
            {
                Onurun_markaismiChanging(value);
                ReportPropertyChanging("urun_markaismi");
                _urun_markaismi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("urun_markaismi");
                Onurun_markaismiChanged();
            }
        }
        private global::System.String _urun_markaismi;
        partial void Onurun_markaismiChanging(global::System.String value);
        partial void Onurun_markaismiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 urunsatissayisi
        {
            get
            {
                return _urunsatissayisi;
            }
            set
            {
                OnurunsatissayisiChanging(value);
                ReportPropertyChanging("urunsatissayisi");
                _urunsatissayisi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urunsatissayisi");
                OnurunsatissayisiChanged();
            }
        }
        private global::System.Int32 _urunsatissayisi;
        partial void OnurunsatissayisiChanging(global::System.Int32 value);
        partial void OnurunsatissayisiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hit
        {
            get
            {
                return _hit;
            }
            set
            {
                OnhitChanging(value);
                ReportPropertyChanging("hit");
                _hit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hit");
                OnhitChanged();
            }
        }
        private Nullable<global::System.Int32> _hit;
        partial void OnhitChanging(Nullable<global::System.Int32> value);
        partial void OnhitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> urungoruntulenmesayisi
        {
            get
            {
                return _urungoruntulenmesayisi;
            }
            set
            {
                OnurungoruntulenmesayisiChanging(value);
                ReportPropertyChanging("urungoruntulenmesayisi");
                _urungoruntulenmesayisi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urungoruntulenmesayisi");
                OnurungoruntulenmesayisiChanged();
            }
        }
        private Nullable<global::System.Int32> _urungoruntulenmesayisi;
        partial void OnurungoruntulenmesayisiChanging(Nullable<global::System.Int32> value);
        partial void OnurungoruntulenmesayisiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> urun_adet
        {
            get
            {
                return _urun_adet;
            }
            set
            {
                Onurun_adetChanging(value);
                ReportPropertyChanging("urun_adet");
                _urun_adet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urun_adet");
                Onurun_adetChanged();
            }
        }
        private Nullable<global::System.Int32> _urun_adet;
        partial void Onurun_adetChanging(Nullable<global::System.Int32> value);
        partial void Onurun_adetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> toplamfiyat
        {
            get
            {
                return _toplamfiyat;
            }
            set
            {
                OntoplamfiyatChanging(value);
                ReportPropertyChanging("toplamfiyat");
                _toplamfiyat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("toplamfiyat");
                OntoplamfiyatChanged();
            }
        }
        private Nullable<global::System.Int32> _toplamfiyat;
        partial void OntoplamfiyatChanging(Nullable<global::System.Int32> value);
        partial void OntoplamfiyatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StokAdedi
        {
            get
            {
                return _StokAdedi;
            }
            set
            {
                OnStokAdediChanging(value);
                ReportPropertyChanging("StokAdedi");
                _StokAdedi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StokAdedi");
                OnStokAdediChanged();
            }
        }
        private Nullable<global::System.Int32> _StokAdedi;
        partial void OnStokAdediChanging(Nullable<global::System.Int32> value);
        partial void OnStokAdediChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="Yorumlar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Yorumlar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Yorumlar object.
        /// </summary>
        /// <param name="yorum_id">Initial value of the yorum_id property.</param>
        public static Yorumlar CreateYorumlar(global::System.Int32 yorum_id)
        {
            Yorumlar yorumlar = new Yorumlar();
            yorumlar.yorum_id = yorum_id;
            return yorumlar;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 yorum_id
        {
            get
            {
                return _yorum_id;
            }
            set
            {
                if (_yorum_id != value)
                {
                    Onyorum_idChanging(value);
                    ReportPropertyChanging("yorum_id");
                    _yorum_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("yorum_id");
                    Onyorum_idChanged();
                }
            }
        }
        private global::System.Int32 _yorum_id;
        partial void Onyorum_idChanging(global::System.Int32 value);
        partial void Onyorum_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kisi_adi
        {
            get
            {
                return _kisi_adi;
            }
            set
            {
                Onkisi_adiChanging(value);
                ReportPropertyChanging("kisi_adi");
                _kisi_adi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kisi_adi");
                Onkisi_adiChanged();
            }
        }
        private global::System.String _kisi_adi;
        partial void Onkisi_adiChanging(global::System.String value);
        partial void Onkisi_adiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String yorum
        {
            get
            {
                return _yorum;
            }
            set
            {
                OnyorumChanging(value);
                ReportPropertyChanging("yorum");
                _yorum = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("yorum");
                OnyorumChanged();
            }
        }
        private global::System.String _yorum;
        partial void OnyorumChanging(global::System.String value);
        partial void OnyorumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tarih
        {
            get
            {
                return _tarih;
            }
            set
            {
                OntarihChanging(value);
                ReportPropertyChanging("tarih");
                _tarih = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tarih");
                OntarihChanged();
            }
        }
        private Nullable<global::System.DateTime> _tarih;
        partial void OntarihChanging(Nullable<global::System.DateTime> value);
        partial void OntarihChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> urun_id
        {
            get
            {
                return _urun_id;
            }
            set
            {
                Onurun_idChanging(value);
                ReportPropertyChanging("urun_id");
                _urun_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urun_id");
                Onurun_idChanged();
            }
        }
        private Nullable<global::System.Int32> _urun_id;
        partial void Onurun_idChanging(Nullable<global::System.Int32> value);
        partial void Onurun_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> onay
        {
            get
            {
                return _onay;
            }
            set
            {
                OnonayChanging(value);
                ReportPropertyChanging("onay");
                _onay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("onay");
                OnonayChanged();
            }
        }
        private Nullable<global::System.Int32> _onay;
        partial void OnonayChanging(Nullable<global::System.Int32> value);
        partial void OnonayChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pcompone_1453Model", Name="Ziyaretci")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ziyaretci : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ziyaretci object.
        /// </summary>
        /// <param name="ziyaretci_id">Initial value of the ziyaretci_id property.</param>
        public static Ziyaretci CreateZiyaretci(global::System.Int32 ziyaretci_id)
        {
            Ziyaretci ziyaretci = new Ziyaretci();
            ziyaretci.ziyaretci_id = ziyaretci_id;
            return ziyaretci;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ziyaretci_id
        {
            get
            {
                return _ziyaretci_id;
            }
            set
            {
                if (_ziyaretci_id != value)
                {
                    Onziyaretci_idChanging(value);
                    ReportPropertyChanging("ziyaretci_id");
                    _ziyaretci_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ziyaretci_id");
                    Onziyaretci_idChanged();
                }
            }
        }
        private global::System.Int32 _ziyaretci_id;
        partial void Onziyaretci_idChanging(global::System.Int32 value);
        partial void Onziyaretci_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ipadress
        {
            get
            {
                return _Ipadress;
            }
            set
            {
                OnIpadressChanging(value);
                ReportPropertyChanging("Ipadress");
                _Ipadress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ipadress");
                OnIpadressChanged();
            }
        }
        private global::System.String _Ipadress;
        partial void OnIpadressChanging(global::System.String value);
        partial void OnIpadressChanged();

        #endregion

    
    }

    #endregion

    
}
